cursor #E3A8B8

foreground #F9F8EA
background #0D0E0F

# black
color0  #38393A
color8  #A7A698

# red
color1  #706D7D
color9  #827E93

# green
color2  #EFEDD9
color10 #EFEDD9

# yellow
color3  #917866
color11 #B18C72

# blue
color4  #EFEDD9
color12 #EFEDD9

# magenta
color5  #EFEDD9
color13 #EFEDD9

# cyan
color6  #EFEDD9
color14 #EFEDD9

# white
color7  #EFEDD9
color15 #EFEDD9
